spring:
#  application:
#    name: order-service
  datasource: # * Configuracion de base de datos
    url: jdbc:postgresql://localhost:5433/order_db
    username: root
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa: # * Configuracion de JPA
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  threads: # * Habilitacion hilos virtuales
    virtual:
      enabled: true
  security: # * Configuracion de autenticacion de id de usuarios por keycloak
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce-realm
order: # * Configuracion de actuator
  enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "refresh, health"
resilience4j: # * Configuracion de circuit breaker
  circuitbreaker:
    instances:
      inventory: # ? Nombre del circuit breaker (debe coincidir con la anotacion de java)
        registerHealthIndicator: true # ? Activacion de vigilancia de actuator
        slidingWindowType: COUNT_BASED # ? Cuente la cantidad de peticion
        slidingWindowSize: 5 # ? El sistema va a mirar el estado de las ultimas 5 peticiones
        failureRateThreshold: 50 # ? El circuit breaker si el 50% o mas de las peticiones fallan
        waitDurationInOpenState: 5s # ? Espera 5 segundos en estado ABIERTO antes de pasar a MEDIO-ABIERTO
        permittedNumberOfCallsInHalfOpenState: 3 # ? Hace 3 llamadas de prueba a MITAD-ABIERTO
  retry: # * Configuracion de retry pattern para consumo de servicio de invetario
    instances:
      inventoryRetry:
        maxAttempts: 3 # ? Numero maximo de intentos
        waitDuration: 2000ms # ? Tiempo entre cada intento
        enableExponentialBackoff: true # ? Activacion de espera exponencia
        exponentialBackoffMultiplier: 2 # ? Multiplica el tiempo de espera por 2 en cada fallo (1s, luego 2s...)
#  timelimiter:
#    instances:
#      inventoryTimeout:
#        timeoutDuration: 3000ms #? Si el servicio tarda mas de 1.5 segundos, corta la comunicacion
#        cancelRunningFuture: true # ? Cancela el hilo secundario si se cumple el timeout
server:
  port: 0
