spring:
  application:
    name: inventory-service
  config: # ! ESPECIFICACION ACCESO A CONFIG SERVER
    import: "optional:configserver:http://localhost:8888"
eureka: # ! CONFIGURACION PARA EUREKA DISCOVERY CLIENT
  instance:
    instance-id: "${spring.application.name}:${random.int}"
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
# * Borramos configuracion y dejamos unicamente el nombre del ms
#  threads: # * Habilitación de hilos virtuales
#    virtual:
#      enabled: true
#  datasource:
#    url: jdbc:mysql://localhost:3307/inventory_db
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#server:
#  port: 8081
